- src/struct_info.rs
It's not meaningful to generate documentation for these methods/fields so this PR allows crates to compile even when they disallow missing documentation.
> Public items which do not have a doc-attribute make the compilation of a crate fail when that crate has attribute #![deny(missing_docs)] applied.
> Add allow(missing_docs) to public builder items

- CHANGELOG.md
- src/struct_info.rs
- tests/no_std.rs
Fixes #9.
The added no_std tests are just a straight copy of the other tests, with `Vec<i32>` changed to `[i32; 3]`.
> Support no_std operation

- CHANGELOG.md
- src/struct_info.rs
- tests/tests.rs
Currently, the macro push type tuples to the end of generics.
Say we have a `Foo<X, Y>` struct, the signature of  generated `FooBuilder` is ` FooBuilder<X, Y, ((), ())>`.
When the original struct has a type parameter with a default like `Foo<X, Y=Bar>`, this will yield a builder of  ` FooBuilder<X, Y=Bar, ((), ())>`. 
Unfortunately, rust compiler complains that
> type parameters with a default must be trailing
In other words, rust only allow a type parameter with a default to be trailing, like  ` FooBuilder<X, ((), ()), Y=Bar>`.
My solution is straight forward: instead of appending all state machine types, insert empty tuples type right before any generic types.
For instance, suppose we have a generic type:
```rust
Foo<'a, 'b, X, Y=Bar>{x:&'a X, y:&'b Y}
```
Insert marker generic types …
> insert type tuples before generic types

- CHANGELOG.md
- src/field_info.rs
- src/struct_info.rs
- tests/tests.rs
Currently, all setters use `Into` trait to gain a flexible and ergonomic API. 
For example, for `Foo{s:String}`, a setter with a signature of `fn s<T: Into<String>>(input:s)` can now accept both `&str` and `String`. 
However, `Into` conversion design confuses rustc when there is any generic type. When the setter get a concrete type, there is no way that rustc can infer what type to convert into. So we have to explicitly describe the generic type, for instance, `Foo::<uszie>::builder().x(0).build()` for `Foo<T>{x:T}`. 
This is really annoying when the number of generic types increases.
Maybe we should offer a method to disable `Into` conversion.
A good way is to implement a field attribute, say `skip_into`, so user can disable conversion on demand.
```rust
struct …
```
> Generic type parameter inference

- src/lib.rs
- src/struct_info.rs
As described in the README, errors when a field has not been set when `build` is called or when the setter is called twice are just `no method` errors.
The suggested implementation is based on the proposed idea from #3. 
It does not provide very clean errors, but still more specific than the (confusing) `no method`.
Errors for missing fields when the `build` method is called only report the first missing field. This allows to keep a number of `impl` equal to the number of fields and avoid an exponential number.
For each field, there is an `impl` containing setter for the field, for builders who already have that field set.
That setter takes as argument an empty enum to cause a compilation error, instead of the field.
This enum has a particular name to explain a bit the error.
The setter …
> Specific errors for missing or repeated fields

- CHANGELOG.md
- src/field_info.rs
- src/struct_info.rs
- tests/tests.rs
I accidentally rustfmt'd the code and I can clean up this PR tomorrow without the formatting changes, but here's a change to support Into for stripped option types.
> Add ability to use both StripOption and AutoInto

- src/struct_info.rs
- tests/tests.rs
It was a bit tricky to figure this out (since I'm using this macro nested inside another much larger one), but I think I've gotten better at debugging proc macros with invalid output now 😅
In any case, thanks for making this crate! It's going to save me a huge amount of work.
I've included the test for this issue a commit earlier than the fix, so if you'd like to preserve bisectable history, please squash them when merging.
> Fix lifetime bounds erroneously preserved in phantom generics

- src/struct_info.rs
I'm about to start work on a pull/feature request, but for now here's a small thing I noticed while using the crate earlier.
The default `.builder()` method docs still mention `Into` regardless of whether that is actually enabled for any of the setters, so I removed the mention entirely.
Alternatively, I could also make it show up only when that setting is enabled on all of them.
> Remove " (they accept `Into` values)" from default builder docs

- src/struct_info.rs
- tests/tests.rs
As `min_const_generics` is going to available in Rust 1.51, I find the generated type parameter ordering is not correct when using with const parameters.
> Fix "type parameters must be declared prior to const parameters"

- CHANGELOG.md
- src/field_info.rs
- src/lib.rs
- src/struct_info.rs
- tests/no_std.rs
- tests/tests.rs
I was having some trouble with pedantic Clippy warnings that seemed hard to fix on my end (as they appear to leak through `Span::mixed_site()` on the `#[derive(TypedBuilder)]` in my outer macro), so I made the adjustments here.
Avoiding those warnings doesn't seem to be part of the existing features, so please consider this a feature request.
I've added a `#![warn(clippy::pedantic)]` to `tests.rs` and `no_std.rs` in that regard, which should be enough to catch any of these issues in the future.
By doing so, I've also noticed that this repository had right single quotation marks `’` in place of apostrophes `'` in parts of the documentation. I've replaced them globally since they were only in contractions.
- - -
I've added `#[allow(clippy::default_trait_access)]` on a few generated methods, …
> Avoid consumer-visible clippy::pedantic warnings

- src/field_info.rs
- src/lib.rs
- src/struct_info.rs
Using the `#[builder(setter(transform = |a: T, b: U| f(a, b)))]` syntax, resolves #53
> Implemented setter(transform), resolves #53

- CHANGELOG.md
- README.md
- examples/complicate_build.rs
- src/lib.rs
- src/struct_info.rs
- tests/tests.rs
Instead of generating a public `build` method, we can generate a private `build` method with a name like `__build()`. With this, users can write a custom build method with complicated logic and even build into another `struct`.  
Say we have a struct `Foo` as following:
```rust
#[derive(PartialEq, TypedBuilder)]
struct Foo {
x: i32,
#[builder(default, setter(strip_option))]
y: Option<i32>,
#[builder(default = 20)]
z: i32,
}
```
This is taken from `example/example.rs`.
The above code will generated a build method as following:
```rust
#[allow(dead_code, non_camel_case_types, missing_docs)]
impl<
__z: FooBuilder_Optional<i32>,
__y: FooBuilder_Optional<Option<i32>>,
> FooBuilder<((i32,), __y, __z)> {
#[allow(clippy::default_trait_access)]
pub fn build(self) -> Foo {
let (x, y, z) = …
```
> feat: add struct attr to replace `build` method with a private method 

- Cargo.toml
- src/field_info.rs
- src/struct_info.rs
- src/util.rs
Closes https://github.com/idanarye/rust-typed-builder/issues/85
There is one change: `#[builder]` and `#[builder = …]` are now just ignored.
We could throw an error by adding the two missing arms to the match of `attr.meta` and then checking the path, but I don't think that we should waste this (minimal) performance on checking attributes that are probably not related to typed-builder.
> Upgrade syn to 2.x

- .github/workflows/ci.yml
If you take a look at the latest CI tests in other PRs, nightly is 10 times faster. This is because of the sparse index that is the default in Rust 1.70
> Use Rust 1.70 in stable for parse index

- CHANGELOG.md
- examples/complicate_build.rs
- examples/example.rs
- examples/example_prefix_suffix.rs
- src/lib.rs
- tests/tests.rs
- typed-builder-macro/src/field_info.rs
- typed-builder-macro/src/struct_info.rs
- typed-builder-macro/src/util.rs
This PR adds support to add prefixes and suffixes to setter methods.
```rust
#[builder(field_defaults(setter(prefix = "with_", suffix = "_value")))]
struct Foo {
x: i32,
y: u32,
}
let foo = Foo::builder().with_x_value(1).with_y_value(2).build();
```
> feat: add support for setter prefix and suffix

- tests/no_type_leakage.rs
- typed-builder-macro/src/struct_info.rs
This PR fixes a private type leak bug in the expanded macro output, by making a small simplification in the implementation.  I also added a test that triggers the bug.
> Fix private type leak

- Cargo.toml
- typed-builder-macro/Cargo.toml
Currently, the newly separated macro crate is missing some important cargo metadata (like the license).  Using a workspace allows the two crates to share the same information.
> Make repository into workspace

- src/lib.rs
Thanks for the effort in maintaining Typed Builder.
Our framework [LibAFL](https://github.com/AFLplusplus/LibAFL) is using Typed Builder in a no_std context and the recent update to 0.15.0 is breaking our library on bare metal targets.
In this PR, I introduce no_std compatibility. There is no downside, just an annotation and an import from core.
If you want to test it, use `cargo +nightly build -Zbuild-std=core --target aarch64-unknown-none` (you may want it in the CI script eventually).
> Add no_std compatibility

- typed-builder-macro/src/struct_info.rs
This PR changes the usage of `_` to `()` inside setters.
When implementing a setter, the code will expand to something like this:
```rust
let (field, _) = self.fields;
```
While this is fine, with Rust 1.73 Clippy will introduce a new pedantic lint [`ignored_unit_patterns`](https://rust-lang.github.io/rust-clippy/master/index.html#/ignored_unit_patterns).  
This will result in warnings on each usage of the `TypedBuilder` macro.
With this one-line change, the expanded code will change to something like this:
```rust
let (field, ()) = self.fields;
```
> Explicitly match unit type inside generated setters

- src/lib.rs
- tests/tests.rs
- typed-builder-macro/src/field_info.rs
- typed-builder-macro/src/struct_info.rs
Very small change to allow a use case for LibAFL where a `default = ` expression needs to mutate another field. Here's a snippet for example:
```rust
/// Sending end on a (unidirectional) sharedmap channel
#[derive(TypedBuilder, Debug)]
#[builder(build_method(into = Result::<LlmpSender<SP>, Error>))]
pub struct LlmpSender<SP>
where
SP: ShMemProvider,
{
/// ID of this sender.
id: ClientId,
#[builder(default = ptr::null_mut())]
/// Ref to the last message this sender sent on the last page.
/// If null, a new page (just) started.
last_msg_sent: *const LlmpMsg,
#[builder(default)]
/// A vec of pages that we previously used, but that have served its purpose
/// (no potential readers are left).
/// Instead of freeing them, we keep them around to potentially reuse them later,
/// if they are …
```
> Mutable assignments variables

- tests/tests.rs
- typed-builder-macro/src/field_info.rs
- typed-builder-macro/src/struct_info.rs
- typed-builder-macro/src/util.rs
This PR adds support for paths of the `build_method(into)` field that contain angle brackets (such as `Arc<Foo>`)
> Add support for paths with angle brackets

- tests/tests.rs
- typed-builder-macro/src/struct_info.rs
This PR adds support for structs with `?Sized` generic parameters. Previously those were not accepted.
Technically this is a breaking change since this changes the internal `PhantomData` type from `PhantomData<(T1, T2)>` to `(PhantomData<T1>, PhantomData<T2>)`, and `Default` is only implemented for tuples of up to 12 items due to missing variadic generics.
Practically no struct should hit this limitation though.
> Add support for `?Sized` generics

- typed-builder-macro/src/struct_info.rs
I fixed the builder method link to work with `builder_method(name=custom_name)`. I also fixed for `build_method(name=custom_name)` as well.
> Fix builder method link of the builder type

- typed-builder-macro/src/builder_attr.rs
- typed-builder-macro/src/lib.rs
- typed-builder-macro/src/struct_info.rs
Thanks for maintaining this great crate. I was to implement a new feature but noticed that it's hard to reuse `TypeBuilderAttr`. I'd like to suggest move `TypeBuilderAttr` to a separate file. Also I moved the entire derive implementation to be the public function of `StructInfo` and make impl functions private, to make its duty clear.
> Refactor implementations of StructInfo::derive and TypeBuilderAttr

- typed-builder-macro/src/struct_info.rs
```
error: binding to `_` prefixed variable with no side-effect
--> fuc_engine/src/ops/remove.rs:32:10
|
32 | #[derive(TypedBuilder, Debug)]
|          ^^^^^^^^^^^^
|
= help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#no_effect_underscore_binding
= note: this error originates in the derive macro `TypedBuilder` (in Nightly builds, run with -Z macro-backtrace for more info)
```
> Allow clippy::no_effect_underscore_binding

- typed-builder-macro/LICENSE-APACHE
- typed-builder-macro/LICENSE-MIT
Both the Apache-2.0 and MIT licenses require that (re)distributed sources contain a copy of the original license text. As of right now, the sources published and redistributed via crates.io for the typed-builder-macro crate do not contain license texts.
This PR adds symbolic links that point at the license texts in the project's root directory, which is enough for "cargo package" / "cargo publish" to resolve and include them when publishing to crates.io in most circumstances (unless you're running the "cargo publish" command on Windows, AFAIK).
> Include license files in typed-builder-macro crate

- tests/no_type_leakage.rs
A contender for the world's smallest PR.
Right now, the code builds with a warning (for me):
```
warning: field `0` is never read
--> tests/no_type_leakage.rs:15:16
|
15 | pub struct Bar(Foo);
|            --- ^^^
|            |
|            field in this struct
|
= note: `#[warn(dead_code)]` on by default
help: consider changing the field to be of unit type to suppress this warning while preserving the field numbering, or remove the field
|
15 | pub struct Bar(());
|             
```
This PR makes the type
```rust
#[allow(unused)]
pub struct Bar(Foo);
```
To suppress that warning.
> Allow unused type in no_type_leakage test

- examples/example.rs
- tests/no_std.rs
- typed-builder-macro/src/field_info.rs
- typed-builder-macro/src/struct_info.rs
I noticed that the builder has support for explicitly provided comments, e.g. via
```rust
#[builder(
default,
setter(strip_option, doc = "Set `y`. If you don't specify a value it'll default to no value.",)
)]
```
However, regular doccomments would be ignored even when no setter-specific `doc` attribute is provided. With this PR, the following is now possible:
```rust
struct Foo {
/// `x` value.
///
/// This field is mandatory.
x: i32,
/// This doccomment is ignored for the setter. 
#[builder(
default,
setter(strip_option, doc = "Set `y`. If you don't specify a value it'll default to no value.",)
)]
y: Option<i32>,
#[builder(default = 20)]
z: i32,
}
```
On the builder, `x(...)` will be documented with the regular doccomment, `y(...)` is documented with the setter attribute as before and …
> Apply field doc-comments to builder methods

- src/lib.rs
This adds an additional `compile_fail` test to ensure the following does not work:
```rust
use typed_builder::TypedBuilder;
struct Foo {
x: i8,
}
let _ = Foo::builder().build();
```
The functionality already worked as expected, it simply didn't seem to be covered by a test.
> Add a compile_fail test for mandatory fields

- CHANGELOG.md
- src/lib.rs
- tests/tests.rs
- typed-builder-macro/src/field_info.rs
- typed-builder-macro/src/struct_info.rs
Fixes #117 using the API described in https://github.com/idanarye/rust-typed-builder/issues/117#issuecomment-2178009713.
```rust
struct SomeStruct {
#[builder(default, setter(strip_option)]
inner: Option<u32>,
#[builder(setter(strip_option(fallback="outer_opt"))]
outer: Option<u32>,
}
/// `strip_option` retains its current behaviour avoiding a breaking change.
/// `strip_option(fallback ="outer_opt")` strips the `Option`, and creates a fallback that still takes the option. 
/// This makes it fully opt-in.
fn new_api(value: Option<u32>) -> SomeStruct {
match value {
None => SomeStruct::builder().outer_opt(None).build(),
Some(v) => SomeStruct::builder().inner(v).outer(v).build(),
}
}
/// `strip_option(fallback ="outer_opt") makes the original `outer` builder method …
```
> feat: add `strip_option(fallback = field_opt)`

- CHANGELOG.md
- src/lib.rs
- tests/tests.rs
- typed-builder-macro/src/field_info.rs
- typed-builder-macro/src/struct_info.rs
> feat: add `strip_option(fallback = field_bool)`

- CHANGELOG.md
- src/lib.rs
- tests/tests.rs
- typed-builder-macro/src/field_info.rs
- typed-builder-macro/src/struct_info.rs
Fixes #153
- Added `ignore_invalid`, `fallback_prefix`, and `fallback_suffix` options to `strip_option` for better customization.
- Improved handling of `strip_option` to support field defaults and non-Option fields when `ignore_invalid` is enabled.
- Added tests for new `strip_option` features to ensure functionality.
> Improve `field_defaults(strip_option)` semantics

- Cargo.toml
- typed-builder-macro/src/struct_info.rs
PR fixes a bug where raw ident prefixes are not stripped from from base method names before assembling prefixed/suffixed fallback method names
> fix: malformed fallback setter method names

- CHANGELOG.md
- Cargo.toml
- src/lib.rs
- tests/tests.rs
- typed-builder-macro/src/field_info.rs
- typed-builder-macro/src/struct_info.rs
- typed-builder-macro/src/util.rs
Love the library! 
This PR adds a `transform_generics` config to allow adding generic parameters and lifetimes to the closure provided by `#[builder(setter(transform = "..."))]`
The goal is to be able to replicate this setter:
```rust
pub fn set_s<M>(s: impl IntoValue<String, M>) -> String {
s.into_value()
}
```
And with this PR can be done as:
```rust
struct Foo {
#[builder(
setter(
transform_generics = "<__Marker>",
transform = |value: impl IntoValue<String, __Marker>| value.into_value()
)
)]
s: String,
}
```
I don't have any preference for this specific syntax, this just seemed to be the simplest non-breaking way to add the functionality, happy to change the implementation if it still adds the same new functionality?
An example of a usecase for this ([real …
> `#[builder(setter(transform_generics = "<...>"))]` to add generics to the `transform` closure.
